### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by vednig** [ozgur/python-firebase#109]
`Traceback (most recent call last):
  File "C:/Users/myprofile/Documents/firebase tests.py", line 9, in <module>
    firebase=firebase(config)
TypeError: 'module' object is not callable`

**I am getting this error in IDLE when I run this code.**

`from firebase import firebase

config = {
  "apiKey": "apiKey",
  "authDomain": "projectId.firebaseapp.com",
  "databaseURL": "https://databaseName.firebaseio.com",
  "storageBucket": "projectId.appspot.com"
}

firebase = firebase(config)`

**Comment by lgozalvez** [comment]
Just:

import firebase

**Comment by vednig** [comment]
Asked the question here too:
https://stackoverflow.com/questions/63875282/firebase-firebaseconfig-typeerror-module-object-is-not-callable 
Then I think there is a problem with my computer. I tried it on PythonAnywhere and it worked so no issue. I think.
