### ISSUE TITLE
Could not install packages due to an EnvironmentError: 403 Client Error

### ISSUE THREAD

**Issue by jbistis** [ozgur/python-firebase#110]
sudo pip install python-firebase and sudo pip install python-firebase --user ...Both commands error with Could not install packages due to an EnvironmentError: 403 Client Error:  Using a Raspberry Pi PRETTY_NAME="Raspbian GNU/Linux 10 (buster)".  I also tried pip3 with the same result.

**Comment by jbistis** [comment]
this worked...   pip3 install firebase

**Comment by baksosapi** [comment]
Both use pip and pip3 got EnvironmentError:403 Client Error: Forbidden for url: https://www.piwheels.org/simple/python-firebase/
