### ISSUE TITLE
Anonymous user authentication not support

### ISSUE THREAD

**Issue by walshie4** [ozgur/python-firebase#32]
Unless I am mistaken it is not currently possible to use anonymous user authentication.

https://www.firebase.com/docs/web/guide/login/anonymous.html

**Comment by kavika13** [comment]
This is a Firebase javascript web API feature that you linked to, not a Firebase REST API feature. As far as I can tell, this library only supports Firebase REST API features currently.

**Comment by walshie4** [comment]
Ahh my bad :stuck_out_tongue_winking_eye:
