### ISSUE TITLE
how to use put?

### ISSUE THREAD

**Issue by doczoidberg** [ozgur/python-firebase#54]
Sorry but I am to stupid to use the put method. Can you give me an example?

**Comment by doczoidberg** [comment]
I needed patch instead of put to update an item....

**Comment by CarMoreno** [comment]
I would like to get some example about put method. I have been tring all noon but right now I don't have success.

**Comment by CarMoreno** [comment]
**[UPDATE]**
This working for me: `firebase_app.put('/alertas', '1', data_firebase)`
This not working for me: `firebase_app.put(url='/alertas', name='1', data=data_firebase, connection=auth)`
