### ISSUE TITLE
New Firebase

### ISSUE THREAD

**Issue by samyoungnyc** [ozgur/python-firebase#65]
Will the new Firebase still work with your library? If not, are you planning to update it?

Thanks for your good work!

**Comment by mark-hoffmann** [comment]
Everything I have checked is working besides the custom authentication. If that could be updated soon it would save me a ton of headaches.

Thanks!

**Comment by paracha3** [comment]
I think this library should be updated to Firebase v3.0.0 REST API. It would be so sweet

**Comment by Mazyod** [comment]
Where do you get the firebase secret in the new dashboard?
