### ISSUE TITLE
js-clients receive updates with post {'print': 'silent'}

### ISSUE THREAD

**Issue by doczoidberg** [ozgur/python-firebase#74]
I pot via:
`result = firebase.post('/users', new_user, {'print': 'silent'}, {'X_FANCY_HEADER': 'VERY FANCY'})`

but my javascript clients still receive updates.

**Comment by b4oshany** [comment]
`{'print': 'silent'}` doesn't stop js-clients from receiving updates, it only returns `None` instead of the snapshot id.
E.g.
```
  result = firebase.post('/users', new_user, {'print': 'pretty'}, {'X_FANCY_HEADER': 'VERY FANCY'})
  print result
  {u'name': u'-Io26123nDHkfybDIGl7'}

  result = firebase.post('/users', new_user, {'print': 'silent'}, {'X_FANCY_HEADER': 'VERY FANCY'})
  print result == None
```
