### ISSUE TITLE
ImportError: No module named firebase

### ISSUE THREAD

**Issue by varun9597** [ozgur/python-firebase#94]
I want to use Firebase in my RaspberryPi 3B+. I have successfully installed python-firebase in raspberry pi and can see the folder along with "firebase.py" file in  -- "/usr/local/lib/python3.5/dist-packages".

While I am trying to send data from my python script to Firebase. I am facing the following issue.

Traceback (most recent call last): 
  File "test2.py", line 2, in <module>
  from firebase import firebase
ImportError: No module named firebase

Please help.

**Comment by fabidick22** [comment]
what version of firebase you are using?
runt this:
`pip list | grep python-firebase`

**Comment by pangoro24** [comment]
@varun9597 did you solve the problem?

**Comment by varun9597** [comment]
@pangoro24 Yes, I just had to run the code using "python3 filename.py"

**Comment by pangoro24** [comment]
@varun9597  just as reference, in my case was, I needed to use 
`sudo pip3 install python-firebase` 
because I have two python versions: 2.7 and 3.5

**Comment by MaqboolSarroya** [comment]
ERROR: Could not find a version that satisfies the requirement python-firebase (from versions: none)
ERROR: No matching distribution found for python-firebase i am facing this error in the terminal in rasbian operating system for raspberry pi any can guide me about this error i want to store data in firebase data base i have running python 3

**Comment by MaqboolSarroya** [comment]
@varun9597 @pangoro24 @fabidick22
